version: '3.8'

volumes:
  pg-dev-data:
  
services:
  pg-dev:
    build:
      context: .
      dockerfile: Dockerfile-pg
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 0.5s
      timeout: 10s
      retries: 10

  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      pg-dev:
        condition: service_healthy
    links:
      - pg-dev
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database" , "${POSTGRE_DB_DSN}", "up"]