CREATE TABLE conversations (
  match_id TEXT PRIMARY KEY REFERENCES match(id) ON DELETE CASCADE,
  chat_rows INTEGER NOT NULL DEFAULT 0,
  day_pass INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0 
);