CREATE TABLE profile_pictures(
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  selected BOOLEAN NOT NULL DEFAULT FALSE,
  file_id NOT NULL REFERENCES file(id) ON DELETE CASCADE
);