CREATE TABLE profile_pictures(
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  selected BOOLEAN NOT NULL DEFAULT FALSE,
  file_id  TEXT NOT NULL REFERENCES file(id) ON DELETE CASCADE
);